stages:
  - build
  - publish

build_dev:
  stage: build
  tags:
    - build_apk
  only:
    - develop
  before_script:
    - apt-get update && apt-get install -y unzip
    # Download and install Android Command Line Tools
    - curl -x socks5h://10.0.1.98:1080 -L -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip    
    - ls -ltrha | grep cmdline
    - unzip cmdline-tools.zip -d /tmp/cmdline-tools
    - mkdir -p /opt/android-sdk/cmdline-tools/latest
    - mv /tmp/cmdline-tools/* /opt/android-sdk/cmdline-tools/latest/
    - rm cmdline-tools.zip
    - mv /opt/android-sdk/cmdline-tools/latest/cmdline-tools/* /opt/android-sdk/cmdline-tools/latest/
    - rmdir /opt/android-sdk/cmdline-tools/latest/cmdline-tools
    - ls -ltrha /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager
    # Set ANDROID_HOME
    - export ANDROID_HOME=/opt/android-sdk
    - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
    # Accept licenses and install required SDK components
    - yes | sdkmanager --licenses || true
    - export HTTP_PROXY=http:://10.0.1.98:1080
    - export HTTPS_PROXY=http:://10.0.1.98:1080
    - sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
  script:
      - ./gradlew assembleRelease
      - export VERSION_NUMBER=$(grep versionName ./composeApp/build.gradle.kts | cut -d '"' -f 2)
      - ls -ltrha .
      - find . -name "*.apk"
      - mv ./app/build/outputs/apk/release/app-release.apk ./app/build/outputs/apk/release/app-debug-$VERSION_NUMBER.apk
  artifacts:
    paths:
      - ./app/build/outputs/apk/release/
    when: on_success
    expire_in: 10 days
  environment:
    name: build

publish_dev:
  stage: publish
  tags:
    - rfid_dev
  only:
    - develop
  script:
      - cp ./app/build/outputs/apk/release/app-debug-$VERSION_NUMBER.apk /opt/rfid_gateway/storage
  environment:
    name: publish

build_prod:
  stage: build
  tags:
    - build_apk
  only:
    - master
  before_script:
    - apt-get update && apt-get install -y unzip
    # Download and install Android Command Line Tools
    - curl -x socks5h://10.0.1.98:1080 -L -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip    
    - ls -ltrha | grep cmdline
    - unzip cmdline-tools.zip -d /tmp/cmdline-tools
    - mkdir -p /opt/android-sdk/cmdline-tools/latest
    - mv /tmp/cmdline-tools/* /opt/android-sdk/cmdline-tools/latest/
    - rm cmdline-tools.zip
    - mv /opt/android-sdk/cmdline-tools/latest/cmdline-tools/* /opt/android-sdk/cmdline-tools/latest/
    - rmdir /opt/android-sdk/cmdline-tools/latest/cmdline-tools
    - ls -ltrha /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager
    # Set ANDROID_HOME
    - export ANDROID_HOME=/opt/android-sdk
    - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
    # Accept licenses and install required SDK components
    - export HTTP_PROXY=http://10.0.1.98:1080
    - export HTTPS_PROXY=http://10.0.1.98:1080
    - yes | sdkmanager --licenses >/dev/null 2>&1 || true
    - sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
  script:
      - ./gradlew assembleRelease
      - export VERSION_NUMBER=$(grep versionName ./composeApp/build.gradle.kts | cut -d '"' -f 2)
      - mv ./app/build/outputs/apk/release/release-$VERSION_NUMBER.apk ./app/build/outputs/apk/release/app-debug-$VERSION_NUMBER.apk
  artifacts:
    paths:
      - ./app/build/outputs/apk/release/
    when: on_success
    expire_in: 10 days
  environment:
    name: build

publish_prod:
  stage: publish
  tags:
    - rfid_prod
  only:
    - master
  script:
      - cp ./app/build/outputs/apk/release/app-debug-$VERSION_NUMBER.apk /opt/rfid_gateway/storage
  environment:
    name: publish
