services:
  vendor_app_dev:
    image:  repo.avakatan.ir/store-app-multiplatform_develop:latest
    container_name: vendor_app_dev
    ports:
      - "HOST_PORT_DEV:CONTAINER_PORT"
    restart: unless-stopped
    profiles:
      - vendor_dev

  vendor_app_prod:
    image:  repo.avakatan.ir/store-app-multiplatform_master:latest
    container_name: vendor_app_prod
    ports:
      - "HOST_PORT_PROD:CONTAINER_PORT"
    restart: unless-stopped
    profiles:
      - vendor_prod
