services:
  vendor_app_dev:
    image:  repo.avakatan.ir/store-app-multiplatform_develop:latest
    container_name: vendor_app_dev
    ports:
      - "HOST_PORT:CONTAINER_PORT"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d 
    restart: unless-stopped
    profiles:
      - vendor_dev

  vendor_app_prod:
    image:  repo.avakatan.ir/store-app-multiplatform_master:latest
    container_name: vendor_app_prod
    ports:
      - "HOST_PORT:CONTAINER_PORT"
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #   - ./nginx/conf.d:/etc/nginx/conf.d
    restart: unless-stopped
    profiles:
      - vendor_prod
