package com.jeanwest.reader.models

/**
 * Represents a carton, a container for a collection of items, within a warehouse or logistics context.
 *
 * @property number A unique identifier for the carton, often a human-readable string (e.g., a carton number).  Defaults to an empty string.
 * @property id A unique numeric identifier for the carton, typically generated by a database or system. Defaults to 0L.
 * @property date The date the carton was created or processed, as a string.  The expected format should be documented elsewhere in the project (e.g., YYYY-MM-DD).  Defaults to an empty string.
 * @property numberOfItems The number of items currently inside the carton.  Defaults to 0.
 * @property operationSource The origin or source of the operation associated with this carton (e.g., "Packing", "Receiving"). Defaults to an empty string.
 * @property operationDes The destination of the operation associated with this carton (e.g., "Shipping", "Storage"). Defaults to an empty string.
 * @property cartonSource The source location of the carton (e.g., a specific area in the warehouse).  Defaults to an empty string.
 * @property cartonDes The destination location of the carton (e.g., a shelf, a loading dock). Defaults to an empty string.
 * @property barcodeTable A mutable list of barcodes associated with the carton.  This could represent barcodes on the carton itself or on items within the carton.  Defaults to an empty mutable list.
 * @property specification Additional information or notes about the carton's contents or handling requirements. Defaults to an empty string.
 * @property isConfirmed A boolean flag indicating whether the carton's contents or data have been verified. Defaults to `false`.
 * @property epcs A list of Electronic Product Code (EPC) identifiers, typically associated with RFID tags on the carton or its contents.  Defaults to an empty list.
 * @property driverOperationId An identifier linking the carton's operation to a specific driver or operator. Defaults to an empty string.
 * @property isConfirmedByRFID A boolean flag indicating whether the carton's contents or data have been confirmed using RFID scanning. Defaults to `false`.
 * @property everyProductHaveEpc A boolean flag indicating whether every item within the carton is expected to have an associated EPC. Defaults to `false`.
 * @property products A */
data class Carton(
    var number: String = "",
    var id: Long = 0L,
    val date: String = "",
    var numberOfItems: Int = 0,
    val operationSource: String = "",
    val operationDes: String = "",
    var cartonSource: String = "",
    var cartonDes: String = "",
    val barcodeTable: MutableList<String> = mutableListOf(),
    val specification: String = "",
    var isConfirmed: Boolean = false,
    val epcs: List<String> = listOf(),
    val driverOperationId: String = "",
    var isConfirmedByRFID: Boolean = false,
    val everyProductHaveEpc: Boolean = false,
    val products: List<CartonItem> = listOf(),
    val epcsToPrimaryKeyMap: MutableMap<String, Long> = mutableMapOf(),
    val shelfAddress: String = "",
)